---
title: "MATH 216 Homework 2 Shiny App"
author: "Emily Goins"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(dplyr)
library(babynames)
library(ggplot2movies)
```


## Inputs and Outputs

You can embed Shiny inputs and outputs in your document. Outputs are automatically updated whenever inputs change.  This demonstrates how a standard R plot can be made interactive by wrapping it in the Shiny `renderPlot` function. The `selectInput` and `sliderInput` functions create the input widgets used to drive the plot.

```{r eruptions, echo=FALSE}
inputPanel(
  # Input choice - comedy or other
  selectInput("Type", label = "Select movie type:", choices = c("Comedies","Other Movies"))
)

renderPlot({
  
  # Generate Plots
  comedies <- movies %>%
    mutate(comedy = ifelse(Comedy == 1, "Comedies", "Other Movies")) %>%
    filter(comedy == input$Type) 
  comedies
  
  ggplot(data=comedies, aes(x=budget, y=rating)) + 
    geom_point() + 
    scale_x_log10() +
    xlab("Budget") +
    ylab("Rating") +
    ggtitle("Ratings According to Budget for Comedies and Other Movies (Please Select")
  
})
```
